import Head from "next/head";
import Image from "next/legacy/image";
import styles from "../styles/Home.module.css";
import {
  ArrowUturnLeftIcon,
  Bars3Icon,
  CalendarDaysIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftRightIcon,
  DocumentChartBarIcon,
  HeartIcon,
  InboxIcon,
  PencilSquareIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  QuestionMarkCircleIcon,
  SparklesIcon,
  TrashIcon,
  UsersIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import { ChevronDownIcon } from "@heroicons/react/20/solid";
import Carousel from "../components/Swiper";
import { ArrowDownIcon, ArrowUpIcon } from "@heroicons/react/20/solid";
import {
  CursorArrowRaysIcon,
  EnvelopeOpenIcon,
} from "@heroicons/react/24/outline";
import { BoltIcon, GlobeAltIcon, ScaleIcon } from "@heroicons/react/24/outline";
import turple from "../public/turple.svg"
import icon from "../public/icon-1.png";
import profile from "../public/profile.jpeg"
import btreat from "../public/btreat.jpeg"
import blog3 from "../public/blog3.jpeg"
import blog2 from "../public/blog2.jpeg"
import   profile1 from "../public/profile1.jpeg"
import   profile2 from "../public/profile2.jpeg"
import   profile3 from "../public/profile3.jpeg"
import   profile4 from "../public/profile4.jpeg"
import   profile5 from "../public/profile5.jpeg"
const stats = [
  {
    id: 1,
    name: "Total Subscribers",
    stat: "71,897",
    icon: icon,
    change: "122",
    changeType: "increase",
  },
  {
    id: 2,
    name: "Avg. Open Rate",
    stat: "58.16%",
    icon: EnvelopeOpenIcon,
    change: "5.4%",
    changeType: "increase",
  },
  {
    id: 3,
    name: "Avg. Click Rate",
    stat: "24.57%",
    icon: CursorArrowRaysIcon,
    change: "3.2%",
    changeType: "decrease",
  },
];
const solutions = [
  {
    name: "Inbox",
    description:
      "Get a better understanding of where your traffic is coming from.",
    href: "#",
    icon: InboxIcon,
  },
  {
    name: "Messaging",
    description: "Speak directly to your customers in a more meaningful way.",
    href: "#",
    icon: ChatBubbleBottomCenterTextIcon,
  },
  {
    name: "Live Chat",
    description: "Your customers' data will be safe and secure.",
    href: "#",
    icon: ChatBubbleLeftRightIcon,
  },
  {
    name: "Knowledge Base",
    description: "Connect with third-party tools that you're already using.",
    href: "#",
    icon: QuestionMarkCircleIcon,
  },
];

const features = [
  {
    name: "Qualified Specialist",
    description:
      "We hire the best specialist to deliver top-notch diagnostic services for you.",
    icon: GlobeAltIcon,
  },
  {
    name: "Modern Equipment",
    description:
      "We use the first-class medical equipment for timely diagnostics of various diseases.",
    icon: ScaleIcon,
  },
  {
    name: "Emergency Diagnostics",
    description:
      "Our emergency diagnostics services help you get the most accurate diagnosis in a minimal time.",
    icon: BoltIcon,
  },
];
const people = [
  {
    name: "Dr. Whitney Francis",
    role: "Chief Medical Officer, Pathologist",
    imageUrl: profile1,
    twitterUrl: "#",
    linkedinUrl: "#"
  },
  {
    name: "Dr. Jane Fowler",
    role: "Clinical Laboratory Technologist",
    imageUrl: profile2,
    twitterUrl: "#",
    linkedinUrl: "#"
  },
  {
    name: "Dr. Eric Snyder",
    role: "MRI Technologist",
    imageUrl: profile3,
    twitterUrl: "#",
    linkedinUrl: "#"
  },
  {
    name: "Dr. Martha Schmidt",
    role: "Chief Medical Officer, Pathologist",
    imageUrl: profile4,
    twitterUrl: "#",
    linkedinUrl: "#"
  },
  {
    name: "Dr. James Wilson",
    role: "Radiology Technician",
    imageUrl: profile5,
    twitterUrl: "#",
    linkedinUrl: "#"
  }

  // More people...
];
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Home() {
  return <div className={styles.container}>
      <Head>
        <title>Appnovia Hospital</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Carousel />
        <section className="relative sm:-mt-24 z-40">
          <div className="mx-auto max-w-6xl">
            <dl className="rounded-lg bg-white shadow-lg sm:grid sm:grid-cols-3">
              <div className="flex flex-col border-b border-gray-100 p-6 text-center sm:border-0 sm:border-r">
                <dt className="order-2 mt-2 text-lg font-medium leading-6 text-gray-500">
                  <div className="flex text-base justify-between">
                    <span>Mon-Fri</span>
                    <span>8:00am-9:00pm</span>
                  </div>
                  <div className="flex text-base py-2 justify-between">
                    <span>Saturday</span>
                    <span>9:00am-5:00pm</span>
                  </div>
                  <div className="flex text-base justify-between">
                    <span>Mon-Fri</span>
                    <span>8:00am-9:00pm</span>
                  </div>
                </dt>
                <dd className="order-1  mb-3 text-xl text-center tracking-tight text-cyan-600">
                  <div className="flex items-center ">
                    <CalendarDaysIcon className="w-auto h-8" />
                    <span className="uppercase mx-4 font-bold">
                      {" "}Opening Hours
                    </span>
                  </div>
                </dd>
              </div>
              <div className="flex flex-col border-t border-b border-gray-100 p-6 text-left sm:border-0 sm:border-l sm:border-r">
                <dt className="order-2 mt-2 pt-3 text-base font-medium leading-6 text-gray-500">
                  The first step towards a healthy life is to schedule an
                  appointment. Please contact our office by phone or complete
                  the appointment request form.
                </dt>
                <dd className="order-1 text-xl  tracking-tight text-cyan-600">
                  <div className="flex items-center ">
                    <PhoneArrowUpRightIcon className="w-auto h-8" />
                    <span className="uppercase mx-4 font-bold">
                      {" "}Appointments
                    </span>
                  </div>
                </dd>
              </div>
              <div className="flex flex-col border-t border-gray-100 p-6 text-left sm:border-0 sm:border-l">
                <dt className="order-2 mt-2 pt-3 text-2xl font-medium leading-6 text-gray-500">
                  <span>
                    <strong>1-800-1234-567</strong>
                  </span>
                  <br />
                  <br />
                  <span className="text-base">Call us!</span>
                </dt>
                <dd className="order-1  text-xl tracking-tight text-cyan-600">
                  <div className="flex items-center ">
                    <CalendarDaysIcon className="w-auto h-8" />
                    <span className="uppercase mx-4 font-bold">
                      Emergency Cases
                    </span>
                  </div>
                </dd>
              </div>
            </dl>
          </div>
        </section>
        <section className="py-20 mx-auto max-w-7xl px-4 sm:px-8">
          <h1 className="text-4xl font-bold tracking-tight sm:text-left sm:text-4xl">
            What Makes Us Different
          </h1>
          <div className="bg-white py-10 sm:py-20 lg:py-20">
            <div className="mx-auto max-w-xl px-6 lg:max-w-7xl lg:px-8">
              {/* <h2 className="sr-only">A better way to send money.</h2> */}
              <dl className="grid grid-cols-1 gap-16 lg:grid lg:grid-cols-3">
                {features.map(feature => <div key={feature.name}>
                    <dt>
                      <div className="flex h-16 w-16 items-center justify-center rounded-full bg-cyan-600 text-white">
                        <feature.icon className="h-14 w-14" aria-hidden="true" />
                      </div>
                      <p className="mt-6 text-lg font-semibold leading-8 tracking-tight text-gray-900">
                        {feature.name}
                      </p>
                    </dt>
                    <dd className="mt-2 text-base leading-7 text-gray-600">
                      {feature.description}
                    </dd>
                  </div>)}
              </dl>
            </div>
          </div>
        </section>
        <section className="bg-fixed bg-center h-full bg-cover custom-img">
          <div className="relative">
            <div className="mx-auto max-w-7xl">
              <div className="absolute inset-0">
                <div className="absolute inset-0 bg-gray-900 bg-opacity-70" />
              </div>
              {/* <div className="absolute inset-0">
                  <img className="h-full w-full bg-fixed object-cover" src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2830&q=80&sat=-100" alt="People working on laptops" />
                  <div className="absolute inset-0 bg-indigo-700 mix-blend-multiply" />
                </div> */}
              <div className="relative px-4 py-16 sm:px-6 sm:py-24 lg:py-32 lg:px-8">
                <h1 className="text-left text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
                  <span className="block text-white">
                    All Kinds Of Diagnostics
                  </span>
                </h1>
                <p className=" mt-6 max-w-lg text-left text-xl text-white sm:max-w-3xl">
                  Medina offers the region’s most comprehensive range of
                  diagnostic services, from MRI to X-ray.
                </p>
                <div className="mt-8 flex gap-x-4 ">
                  <button className="inline-block rounded-xl bg-white px-4 py-1.5 text-base font-semibold leading-7 text-black hover:text-white shadow-sm ring-1  hover:bg-cyan-600">
                    Free Consultation
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="bg-white">
            <div className="mx-auto max-w-7xl py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
              <div className="text-center">
                <h2 className="text-lg font-semibold text-cyan-600">
                  What we offer
                </h2>
                <p className="mt-1 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl lg:text-6xl">
                  Our Services
                </p>
                <p className="mx-auto mt-5 max-w-xl text-xl text-gray-500">
                  At our clinic, you can experience the best and the most
                  extensive range of diagnostic services in the state. Feel
                  free to browse our website for more information.
                </p>
              </div>
              <div className="grid grid-cols-1 pt-20 gap-5 lg:grid-cols-4 sm:grid-cols-2">
                <div className="relative flex items-end justify-start w-full text-left bg-center bg-cover h-96 dark:bg-gray-500 testing">
                  <div className="absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-b dark:via-transparent dark:from-transparent dark:to-gray-900" />
                  <div className="absolute top-0 left-0 right-0 flex items-center justify-between mx-5 mt-3" />
                  <h2 className="z-10 p-5">
                    <a rel="noopener noreferrer" href="#" className="font-medium text-md hover:underline dark:text-gray-100">
                      Inventore reiciendis aliquam excepturi
                    </a>
                  </h2>
                </div>
                <div className="relative flex items-end justify-start w-full text-left bg-center bg-cover h-96 dark:bg-gray-500 mri">
                  <div className="absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-b dark:via-transparent dark:from-transparent dark:to-gray-900" />
                  <div className="absolute top-0 left-0 right-0 flex items-center justify-between mx-5 mt-3" />
                  <h2 className="z-10 p-5">
                    <a rel="noopener noreferrer" href="#" className="font-medium text-md hover:underline dark:text-gray-100">
                      Inventore reiciendis aliquam excepturi
                    </a>
                  </h2>
                </div>
                <div className="relative flex items-end justify-start w-full text-left bg-center bg-cover h-96 dark:bg-gray-500 equipment">
                  <div className="absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-b dark:via-transparent dark:from-transparent dark:to-gray-900" />
                  <div className="absolute top-0 left-0 right-0 flex items-center justify-between mx-5 mt-3" />
                  <h2 className="z-10 p-5">
                    <a rel="noopener noreferrer" href="#" className="font-medium text-md hover:underline dark:text-gray-100">
                      Inventore reiciendis aliquam excepturi
                    </a>
                  </h2>
                </div>
                <div className="relative flex items-end justify-start w-full text-left bg-center bg-cover h-96  pregnancy">
                  <div className="absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-b dark:via-transparent dark:from-transparent dark:to-gray-900" />
                  <div className="absolute top-0 left-0 right-0 flex items-center justify-between mx-5 mt-3" />
                  <h2 className="z-10 p-5">
                    <a rel="noopener noreferrer" href="#" className="font-medium text-md hover:underline dark:text-gray-100">
                      Inventore reiciendis aliquam excepturi
                    </a>
                  </h2>
                </div>
                {/* <div className="relative flex items-end justify-start w-full text-left bg-center bg-cover h-96 dark:bg-gray-500 ray">
                  <div className="absolute top-0 bottom-0 left-0 right-0 bg-gradient-to-b dark:via-transparent dark:from-transparent dark:to-gray-900" />
                  <div className="absolute top-0 left-0 right-0 flex items-center justify-between mx-5 mt-3" />
                  <h2 className="z-10 p-5">
                    <a rel="noopener noreferrer" href="#" className="font-medium text-md hover:underline dark:text-gray-100">
                      Inventore reiciendis aliquam excepturi
                    </a>
                  </h2>
                </div> */}
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="mx-auto max-w-7xl py-12 px-4 text-center sm:px-6 lg:px-4 lg:py-24">
            <div className="space-y-12">
              <div className="space-y-5 sm:mx-auto sm:max-w-xl sm:space-y-4 lg:max-w-5xl">
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                  Meet our team
                </h2>
                <p className="text-xl text-gray-500">
                  Ornare sagittis, suspendisse in hendrerit quis. Sed dui
                  aliquet lectus sit pretium egestas vel mattis neque.
                </p>
              </div>
              <ul role="list" className="mx-auto space-y-16 sm:grid sm:grid-cols-2 sm:gap-16 sm:space-y-0  lg:grid-cols-5">
                {people.map(person => <li key={person.name}>
                    <div className="space-y-6">
                      <Image className="mx-auto h-40 w-40 rounded-full xl:h-48 xl:w-48" src={person.imageUrl} alt="" />
                      <div className="space-y-2">
                        <div className="space-y-1 text-lg font-medium leading-6">
                          <h3>
                            {person.name}
                          </h3>
                          <p className="text-cyan-600">
                            {person.role}
                          </p>
                        </div>
                        <ul role="list" className="flex justify-center space-x-5">
                          <li>
                            <a href={person.twitterUrl} className="text-gray-400 hover:text-gray-500">
                              <span className="sr-only">Twitter</span>
                              <svg className="h-5 w-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M6.29 18.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0020 3.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.073 4.073 0 01.8 7.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 010 16.407a11.616 11.616 0 006.29 1.84" />
                              </svg>
                            </a>
                          </li>
                          <li>
                            <a href={person.linkedinUrl} className="text-gray-400 hover:text-gray-500">
                              <span className="sr-only">LinkedIn</span>
                              <svg className="h-5 w-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M16.338 16.338H13.67V12.16c0-.995-.017-2.277-1.387-2.277-1.39 0-1.601 1.086-1.601 2.207v4.248H8.014v-8.59h2.559v1.174h.037c.356-.675 1.227-1.387 2.526-1.387 2.703 0 3.203 1.778 3.203 4.092v4.711zM5.005 6.575a1.548 1.548 0 11-.003-3.096 1.548 1.548 0 01.003 3.096zm-1.337 9.763H6.34v-8.59H3.667v8.59zM17.668 1H2.328C1.595 1 1 1.581 1 2.298v15.403C1 18.418 1.595 19 2.328 19h15.34c.734 0 1.332-.582 1.332-1.299V2.298C19 1.581 18.402 1 17.668 1z" clipRule="evenodd" />
                              </svg>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </li>)}
              </ul>
            </div>
          </div>
        </section>
        {/* testimonials */}
        <section className="py-20">
          <div className="mx-auto max-w-7xl md:grid md:grid-cols-2 md:px-6 lg:px-8">
            <div className="py-12 px-4 sm:px-6 md:flex md:flex-col md:border-r md:border-indigo-900 md:py-16 md:pl-0 md:pr-10 lg:pr-16">
              <div className="md:flex-shrink-0">
                <Image  className="h-12" src={turple} alt="Tuple" />
              </div>
              <blockquote className="mt-6 md:flex md:flex-grow md:flex-col">
                <div className="relative text-lg font-medium text-black md:flex-grow">
                  <svg className="absolute top-0 left-0 h-8 w-8 -translate-x-3 -translate-y-2 transform text-cyan-500" fill="currentColor" viewBox="0 0 32 32" aria-hidden="true">
                    <path d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z" />
                  </svg>
                  <p className="relative">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Nemo expedita voluptas culpa sapiente alias molestiae.
                    Numquam corrupti in laborum sed rerum et corporis.
                  </p>
                  <footer className="mt-3">
                    <div className="flex items-start">
                      <div className="inline-flx flex-shrink-0 items-center rounded-full border-2 border-white">
                        <Image height={70} width={70} className=" w-auto object-cover  rounded-full" src={profile} alt="profile image" />
                      </div>
                      <div className="ml-4 mt-5">
                        <div className="text-base font-medium text-black">
                          Judith Black
                        </div>
                        {/* <div className="text-base font-medium text-black">
                          CEO, Tuple
                        </div> */}
                      </div>
                    </div>
                  </footer>
                </div>
              </blockquote>
            </div>
          </div>
        </section>
        {/* New section */}
        <section className="bg-fixed bg-center h-full bg-cover pedia">
          <div className="relative">
            <div className="mx-auto max-w-7xl">
              <div className="absolute inset-0">
                <div className="absolute inset-0 bg-gray-900 bg-opacity-50" />
              </div>
              {/* <div className="absolute inset-0">
                  <img className="h-full w-full bg-fixed object-cover" src="https://images.unsplash.com/photo-1521737852567-6949f3f9f2b5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2830&q=80&sat=-100" alt="People working on laptops" />
                  <div className="absolute inset-0 bg-indigo-700 mix-blend-multiply" />
                </div> */}
              <div className="relative px-4 py-16 sm:px-6 sm:py-24 lg:py-32 lg:px-8">
                <h1 className="text-left text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">
                  <span className="block text-white">
                    Pediatric Diagnostics
                  </span>
                </h1>
                <p className=" mt-6 max-w-lg text-left text-xl text-white sm:max-w-3xl">
                  Our center provides a vast range of pediatric diagnostic
                  services for children all over our state.nsive range of
                  diagnostic services, from MRI to X-ray.
                </p>
                <div className="mt-8 flex gap-x-4 ">
                  <button className="inline-block rounded-xl bg-white px-4 py-1.5 text-base font-semibold leading-7 text-black hover:text-white shadow-sm ring-1  hover:bg-cyan-600">
                    Free Consultation
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-6 mx-auto max-w-7xl  px-8 sm:py-12 ">
          <div className=" p-6 mx-auto space-y-8">
            <div className=" sm:space-y-4 ">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                Latest Blog Posts
              </h2>
            </div>
            <div className="grid grid-cols-1 gap-x-4 gap-y-8 md:grid-cols-2 lg:grid-cols-3">
              <article className="flex flex-col ">
                <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum">
                <Image alt="" className="object-cover w-full h-52 dark:bg-gray-500" src={btreat} />
                </a>
                <div className="flex flex-col flex-1 p-6">
                  <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum" />
                  {/* <a rel="noopener noreferrer" href="#" className="text-xs tracking-wider uppercase hover:underline dark:text-violet-400">
                    Convenire
                  </a> */}
                  <h3 className="flex-1 py-2 text-lg font-semibold leading-snug">
                    Reasons to Visit a Breast Specialist
                  </h3>
                  <span className="text-sm">
                    There are a lot of women that are unaware of the numerous
                    risks associated with their health and eventually ignore
                    the importance of visiting...
                  </span>
                  <div className="flex flex-wrap justify-between pt-3 space-x-2 text-xs dark:text-gray-400">
                    <span>June 1, 2020</span>
                    <span>2.1K views</span>
                  </div>
                </div>
              </article>
              <article className="flex flex-col ">
                <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum">
                  <Image alt="" className="object-cover w-full h-52 dark:bg-gray-500" src={blog2} />
                </a>
                <div className="flex flex-col flex-1 p-6">
                  <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum" />
                  {/* <a rel="noopener noreferrer" href="#" className="text-xs tracking-wider uppercase hover:underline dark:text-violet-400">
                    Convenire
                  </a> */}
                  <h1 className="flex-1 py-2 text-lg font-bold ">
                    Picking the Right Diagnostic Services for Efficient
                    Results
                  </h1>
                  <span className="text-sm">
                    There have been a lot of cases in which people were not
                    provided with accurate reports that eventually affected
                    their medical treatment. There is always...
                  </span>
                  <div className="flex flex-wrap justify-between pt-3 space-x-2 text-xs dark:text-gray-400">
                    <span>June 2, 2020</span>
                    <span>2.2K views</span>
                  </div>
                </div>
              </article>
              <article className="flex flex-col ">
                <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum">
                  <Image alt="" className="object-cover w-full h-52 dark:bg-gray-500" src={blog3} />
                </a>
                <div className="flex flex-col flex-1 p-6">
                  <a rel="noopener noreferrer" href="#" aria-label="Te nulla oportere reprimique his dolorum" />
                  {/* <a rel="noopener noreferrer" href="#" className="text-xs tracking-wider uppercase hover:underline dark:text-violet-400">
                    Convenire
                  </a> */}
                  <h3 className="flex-1 py-2 text-lg font-semibold leading-snug">
                    Preparing for an ECG in 8 Easy Steps: Tips From Our
                    Diagnosticians
                  </h3>
                  <span className="text-sm">
                    An ECG stands for an "electrocardiogram," which is a test
                    that measures and records the electrical activity of the
                    heart. It is used by doctors to obtain...
                  </span>
                  <div className="flex flex-wrap justify-between pt-3 space-x-2 text-xs dark:text-gray-400">
                    <span>June 3, 2020</span>
                    <span>2.3K views</span>
                  </div>
                </div>
              </article>
            </div>
          </div>
        </section>
      </main>

      {/* <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>;
}
